//Actions for viewing scouts
export const CHANGE_USERNAME = 'CHANGE_USERNAME'
export const CHANGE_YEAR = 'CHANGE_YEAR'

//Actions for changing or adding scouts
export const CHANGE_DATA = 'CHANGE_DATA'
export const CHANGE_SHEET_ENTRY = 'CHANGE_SHEET_ENTRY'
export const CHANGE_NEW_USER = 'CHANGE_NEW_USER'
export const SUBMIT_NEW_USER = 'SUBMIT_NEW_USER'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const CHANGE_CUSTOMER_NAME = 'CHANGE_CUSTOMER_NAME'
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER'
export const GET_SCOUT_INFO = 'GET_SCOUT_INFO'
export const CHANGE_CUSTOMER_PROPERTY = 'CHANGE_CUSTOMER_PROPERTY'
export const ADD_LEAD = 'ADD_LEAD'
export const REMOVE_LEAD = 'REMOVE_LEAD'

//Actions for changing or adding customers
export const CHANGE_STATIC_CUSTOMER_DATA = 'CHANGE_STATIC_CUSTOMER_DATA'
export const ADD_NEW_STATIC_CUSTOMER = 'ADD_NEW_STATIC_CUSTOMER'
export const RESET_NEW_STATIC_CUSTOMER = 'RESET_NEW_STATIC_CUSTOMER'

//Async actions
export const REQUEST_SCOUT = 'REQUEST_SCOUT'
export const REQUEST_SCOUT_POST = 'REQUEST_SCOUT_POST'
export const SCOUT_POST_RESULT = 'SCOUT_POST_RESULT'
export const RECEIVE_SCOUT = 'RECEIVE_SCOUT'
export const REQUEST_LEAD_POST = 'REQUEST_LEAD_POST'
export const LEAD_POST_RESULT = 'LEAD_POST_RESULT'
export const CUSTOMER_POST_RESULT = 'CUSTOMER_POST_RESULT'
export const REQUEST_CUSTOMER_POST = 'REQUEST_CUSTOMER_POST'
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS'
export const REQUEST_SHEET_POST = 'REQUEST_SHEET_POST'
export const SHEET_POST_RESULT = 'SHEET_POST_RESULT'
export const RECEIVE_SALESHEETS = 'RECEIVE_SALESHEETS'

//Authentication actions
export const POPULATE_A0_USER = 'POPULATE_A0_USER'
export const CHANGE_A0_USER = 'CHANGE_A0_USER'
