//Actions for viewing scouts
export const CHANGE_USERNAME = 'CHANGE_USERNAME'

//Actions for changing or adding scouts
export const CHANGE_DATA = 'CHANGE_DATA'
export const CHANGE_NEW_USER = 'CHANGE_NEW_USER'
export const SUBMIT_NEW_USER = 'SUBMIT_NEW_USER'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const CHANGE_CUSTOMER_NAME = 'CHANGE_CUSTOMER_NAME'
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER'
export const GET_SCOUT_INFO = 'GET_SCOUT_INFO'
export const CHANGE_CUSTOMER_PROPERTY = 'CHANGE_CUSTOMER_PROPERTY'

//Actions for changing or adding customers
export const CHANGE_STATIC_CUSTOMER_DATA = 'CHANGE_STATIC_CUSTOMER_DATA'
export const ADD_NEW_STATIC_CUSTOMER = 'ADD_NEW_STATIC_CUSTOMER'

//Async actions
export const FETCH_SCOUT = 'FETCH_SCOUT'
export const REQUEST_SCOUT = 'REQUEST_SCOUT'
export const RECEIVE_SCOUT = 'RECEIVE_SCOUT'
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS'
export const REQUEST_CUSTOMERS = 'REQUEST_CUSTOMERS'
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS'
export const FETCH_SALESHEETS = 'FETCH_SALESHEETS'
export const REQUEST_SALESHEETS = 'REQUEST_SALESHEETS'
export const RECEIVE_SALESHEETS = 'RECEIVE_SALESHEETS'
